Application/WebApp/Areas/LittlePony/Controllers/DialogDemoController.cs
using System.Web.Mvc;
using Smt.Atomic.CrossCutting.Common.Consts;
using Smt.Atomic.Presentation.Common.Attributes;
using Smt.Atomic.Presentation.Renderers.Controllers;
using Smt.Atomic.Presentation.Renderers.Helpers;
using Smt.Atomic.Presentation.Renderers.Interfaces;
using Smt.Atomic.Presentation.Renderers.Models.Dialogs;
using Smt.Atomic.WebApp.Areas.LittlePony.Models;
using Smt.Atomic.WebApp.Areas.LittlePony.Resources;

namespace Smt.Atomic.WebApp.Areas.LittlePony.Controllers
{
    [AtomicAuthorize]
    public class DialogDemoController : AtomicController
    {
        public DialogDemoController(IBaseControllerDependencies baseDependencies) 
            : base(baseDependencies)
        {
            Layout.Parameters.AddParameter<int>(ParameterKeys.TemporaryDocumentMaxUploadChunkSize);
            Layout.Parameters.AddParameter<int>(ParameterKeys.UploadPreviewImageMaxDimension);
            Layout.Parameters.AddParameter<int>(ParameterKeys.UploadCropImageMaxDimension);
        }

        public ActionResult Index()
        {
            Layout.PageTitle = DialogsDemoResources.IndexPageTitle;
            Layout.PageHeader = DialogsDemoResources.IndexPageHeader;

            return View();
        }

        [HttpPost]
        public ActionResult EditPersonDialog(int id)
        {
            var model = new PersonModel
            {
                FirstName = "Steven",
                LastName = "Seagal"
            };

            var dialogModel = new ModelBasedDialogViewModel<PersonModel>(model)
            {
                Title = string.Format(DialogsDemoResources.DialogsDemoControllerEditPersonDialogTitleFormat, model.GetFullName())
            };

            return PartialView(dialogModel);
        }

        [HttpPost]
        public ActionResult ValidatePersonDialog(PersonModel model)
        {
            if (ModelState.IsValid)
            {
                return DialogHelper.Redirect(this, Url.Action("Index", new { it = "worked" }));
            }

            var dialogModel = new ModelBasedDialogViewModel<PersonModel>(model)
            {
                Title = string.Format(DialogsDemoResources.DialogsDemoControllerEditPersonDialogTitleFormat, model.GetFullName())
            };

            return PartialView("EditPersonDialog", dialogModel);
        }
    }
}

Application/WebApp/Areas/LittlePony/Views/DialogDemo/EditPersonDialog.cshtml
@using Smt.Atomic.Presentation.Renderers.Bootstrap.Helpers
@using Smt.Atomic.WebApp.Extensions
@model Smt.Atomic.Presentation.Renderers.Models.Dialogs.ModelBasedDialogViewModel<Smt.Atomic.WebApp.Areas.LittlePony.Models.PersonModel>

@using (Html.BeginCommonDialog(Model))
{
    using (Html.BeginForm("ValidatePersonDialog", "DialogDemo", null, FormMethod.Post, new {@class = "form-horizontal"}))
    {
        @*This is a temporary approach - until we have the form renderers handy*@
        @Html.ValidationSummaryAsAlerts(true)
        @Html.Bootstrap().EditorForModel(Model.Model)
    }
}

Application/WebApp/Areas/LittlePony/Views/DialogDemo/Index.cshtml
@using Smt.Atomic.Presentation.Common.Consts
@using Smt.Atomic.WebApp.Areas.LittlePony.Resources

<h3>@(DialogsDemoResources.IndexAlertSectionTitle)</h3>
<div>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert1HtmlMessage)')">@(DialogsDemoResources.IndexAlert1ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert2HtmlMessage)', '@(DialogsDemoResources.IndexAlert2Title)')">@(DialogsDemoResources.IndexAlert2ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert3HtmlMessage)', '@(DialogsDemoResources.IndexAlert3Title)', null, null, '@(DialogsDemoResources.IndexAlert3OkButtonText)')">@(DialogsDemoResources.IndexAlert3ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert4HtmlMessage)', '@(DialogsDemoResources.IndexAlert4Title)', null, '@(Glyphicons.ThumbsUp)')">@(DialogsDemoResources.IndexAlert4ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert5HtmlMessage)', '@(DialogsDemoResources.IndexAlert5Title)', function (eventArgs) { if (eventArgs.isOk) { alert('@(DialogsDemoResources.IndexAlert5OnOkAlertMessage)'); } })">@(DialogsDemoResources.IndexAlert5ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert6HtmlMessage)', '@(DialogsDemoResources.IndexAlert6Title)', function (eventArgs) { switch (eventArgs.buttonTag) { case 'ok': alert('@(DialogsDemoResources.IndexAlert6OnOkAlertMessage)'); break; case 'other': alert('@(DialogsDemoResources.IndexAlert6OnOtherAlertMessage)'); break; }})">@(DialogsDemoResources.IndexAlert6ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.alert('@(DialogsDemoResources.IndexAlert7HtmlMessage1)', '@(DialogsDemoResources.IndexAlert7Title1)', function (eventArgs) { if (eventArgs.isOk) { CommonDialogs.alert('@(DialogsDemoResources.IndexAlert7HtmlMessage2)', '@(DialogsDemoResources.IndexAlert7Title2)', function (eventArgs) { if (eventArgs.buttonTag == 'ok') { alert('@(DialogsDemoResources.IndexAlert7OnOkAlertMessage)'); } }, '@(Glyphicons.InfoSign)'); }}, '@(Glyphicons.WarningSign)', '@(DialogsDemoResources.IndexAlert7OkButtonText)')">@(DialogsDemoResources.IndexAlert7ButtonText)</button>
</div>

<h3>@(DialogsDemoResources.IndexConfirmSectionTitle)</h3>
<div>
    <button class="btn" onclick="CommonDialogs.confirm('@(DialogsDemoResources.IndexConfirm1HtmlMessage)')">@(DialogsDemoResources.IndexConfirm1ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.confirm('@(DialogsDemoResources.IndexConfirm2HtmlMessage)', '@(DialogsDemoResources.IndexConfirm2Title)')">@(DialogsDemoResources.IndexConfirm2ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.confirm('@(DialogsDemoResources.IndexConfirm3HtmlMessage)', '@(DialogsDemoResources.IndexConfirm3Title)', null, null, '@(DialogsDemoResources.IndexConfirm3OkButtonText)')">@(DialogsDemoResources.IndexConfirm3ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.confirm('@(DialogsDemoResources.IndexConfirm4HtmlMessage)', '@(DialogsDemoResources.IndexConfirm4Title)', null, null, '@(DialogsDemoResources.IndexConfirm4OkButtonText)', '@(DialogsDemoResources.IndexConfirm4CancelButtonText)')">@(DialogsDemoResources.IndexConfirm4ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.confirm('@(DialogsDemoResources.IndexConfirm5HtmlMessage)', '@(DialogsDemoResources.IndexConfirm5Title)', function (eventArgs) { switch (eventArgs.buttonTag) { case 'ok': alert('@(DialogsDemoResources.IndexConfirm5OnOkAlertText)'); break; case 'cancel': alert('@(DialogsDemoResources.IndexConfirm5OnCancelAlertText)'); break; case 'other': alert('@(DialogsDemoResources.IndexConfirm5OnOtherAlertText)'); break; }})">@(DialogsDemoResources.IndexConfirm5ButtonText)</button>
</div>

<h3>@(DialogsDemoResources.IndexPromptSectionTitle)</h3>
<div>
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt1HtmlMessage)')">@(DialogsDemoResources.IndexPrompt1ButtonText)</button> 
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt2HtmlMessage)', '@(DialogsDemoResources.IndexPrompt2Title)')">@(DialogsDemoResources.IndexPrompt2ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt3HtmlMessage)', '@(DialogsDemoResources.IndexPrompt3Title)', '@(DialogsDemoResources.IndexPrompt3InputLabel)')">@(DialogsDemoResources.IndexPrompt3ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt4HtmlMessage)', '@(DialogsDemoResources.IndexPrompt4Title)', null, null, null, '@(DialogsDemoResources.IndexPrompt4OkButtonText)')">@(DialogsDemoResources.IndexPrompt4ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt5HtmlMessage)', '@(DialogsDemoResources.IndexPrompt5Title)', null, null, null, '@(DialogsDemoResources.IndexPrompt5OkButtonText)', '@(DialogsDemoResources.IndexPrompt5CancelButtonText)')">@(DialogsDemoResources.IndexPrompt5ButtonText)</button>
    <button class="btn" onclick="CommonDialogs.prompt('@(DialogsDemoResources.IndexPrompt6HtmlMessage)', null, null, function (eventArgs) { switch(eventArgs.buttonTag) { case 'ok': alert('@(DialogsDemoResources.IndexPrompt6OnOkAlertText)' + eventArgs.enteredText); break; case 'cancel': alert('@(DialogsDemoResources.IndexPrompt6OnCancelAlertText)'); break; }})">@(DialogsDemoResources.IndexPrompt6ButtonText)</button> 
</div>

<h3>@(DialogsDemoResources.IndexShowDialogSectionTitle)</h3>
<div>
    <button class="btn" onclick="Dialogs.showDialog({ actionUrl: '@(Url.Action("EditPersonDialog"))', formData: { id: 1 } })">@(DialogsDemoResources.IndexShowDialogButtonText)</button>
</div>


<h3>@(DialogsDemoResources.IndexShowModelSectionTitle)</h3>
<div>
    <button class="btn" onclick="Dialogs.showModel('Models.PersonModel', '@(DialogsDemoResources.IndexShowModel1Title)', function (eventArgs) { if (eventArgs.isOk) { CommonDialogs.alert(Strings.format('@(DialogsDemoResources.IndexShowModel1AlertHtmlMessageFormat)', eventArgs.model.LastName), '@(DialogsDemoResources.IndexShowModel1AlertOkButtonText)'); }})">@(DialogsDemoResources.IndexShowModel1ButtonText)</button>
    <button class="btn" onclick="Dialogs.showModel('Some.Model.That.Does.Not.Exist', '@(DialogsDemoResources.IndexShowModel2Title)', function (eventArgs) { if (eventArgs.isOk) { CommonDialogs.alert(Strings.format('@(DialogsDemoResources.IndexShowModel2AlertHtmlMessageFormat)', eventArgs.model!=null ? eventArgs.model.LastName : ''), '@(DialogsDemoResources.IndexShowModel2AlertOkButtonText)'); }})">@(DialogsDemoResources.IndexShowModel2ButtonText)</button>
</div>